### ISSUE TITLE
[TODO] Tasks for release

### ISSUE THREAD

**Issue by terazus** [ISA-tools/isa-api#469]
- [x] Force stable identifiers for serialization to RDF (low priority)
- [x] Improve json context @proccaserra 
- [x] Review deprecated functions from ISA-tab that should be used by galaxy workflows
- [x] Review methods from mtbls
- [x] Remove ISA schemas v2 @proccaserra 
- [x] Change the schema version to draf07 or 2020-12 @proccaserra 
- [x] Remove materials from ISA schemas @proccaserra 
- [x] Move contexts files to a separate repo. Under each vocabulary directory, create a subdir for each version. Also don't forget to change the identifiers of the schemas. @proccaserra 
- [x] Adapt isa-tools to get the context files from the new repo. @terazus
